{
  "openapi": "3.0.1",
  "info": {
    "title": "ConsumerDataStandards",
    "description": "API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right. <br/><br/>Useful links:<ul><li><a href=\"https://uatopenbank.newcastlepermanent.com.au/.well-known/openid-configuration\">OIDC Discovery Document</a></li></ul>",
    "contact": {
      "name": "Consumer Data Standards",
      "url": "https://consumerdatastandards.gov.au/",
      "email": "cdr-data61@csiro.au"
    },
    "license": {
      "name": "MIT License",
      "url": "https://opensource.org/licenses/MIT"
    },
    "version": "1.36.0"
  },
  "servers": [
    {
      "url": "https://openbank-secure.newcastlepermanent.com.au/cds-au/v1"
    }
  ],
  "paths": {
    "/banking/accounts": {
      "get": {
        "tags": [
          "Banking",
          "Accounts"
        ],
        "summary": "Get Accounts",
        "description": "Obtain a list of accounts",
        "operationId": "listAccounts",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:accounts.basic:read"
            ]
          },
          {
            "default": [
              "bank:accounts.basic:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/accounts/balances": {
      "get": {
        "tags": [
          "Banking",
          "Accounts"
        ],
        "summary": "Get Bulk Balances",
        "description": "Obtain balances for multiple, filtered accounts",
        "operationId": "listBalancesBulk",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:accounts.basic:read"
            ]
          },
          {
            "default": [
              "bank:accounts.basic:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      },
      "post": {
        "tags": [
          "Banking",
          "Accounts"
        ],
        "summary": "Get Balances For Specific Accounts",
        "description": "Obtain balances for a specified list of accounts",
        "operationId": "listBalancesSpecificAccounts",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:accounts.basic:read"
            ]
          },
          {
            "default": [
              "bank:accounts.basic:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/accounts/{accountId}/balance": {
      "get": {
        "tags": [
          "Banking",
          "Accounts"
        ],
        "summary": "Get Account Balance",
        "description": "Obtain the balance for a single specified account",
        "operationId": "getBalance",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:accounts.basic:read"
            ]
          },
          {
            "default": [
              "bank:accounts.basic:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/accounts/{accountId}": {
      "get": {
        "tags": [
          "Banking",
          "Accounts"
        ],
        "summary": "Get Account Detail",
        "description": "Obtain detailed information on a single account",
        "operationId": "getAccountDetail",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:accounts.detail:read"
            ]
          },
          {
            "default": [
              "bank:accounts.detail:read"
            ]
          }
        ],
        "x-version": "4",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/accounts/{accountId}/transactions": {
      "get": {
        "tags": [
          "Banking",
          "Accounts"
        ],
        "summary": "Get Transactions For Account",
        "description": "Obtain transactions for a specific account.\n\nSome general notes that apply to all end points that retrieve transactions:\n\n- Where multiple transactions are returned, transactions should be ordered according to effective date in descending order\n- As the date and time for a transaction can alter depending on status and transaction type two separate date/times are included in the payload. There are still some scenarios where neither of these time stamps is available. F[...]",
        "operationId": "getTransactions",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:transactions:read"
            ]
          },
          {
            "default": [
              "bank:transactions:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/accounts/{accountId}/transactions/{transactionId}": {
      "get": {
        "tags": [
          "Banking",
          "Accounts"
        ],
        "summary": "Get Transaction Detail",
        "description": "Obtain detailed information on a transaction for a specific account",
        "operationId": "getTransactionDetail",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:transactions:read"
            ]
          },
          {
            "default": [
              "bank:transactions:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/accounts/{accountId}/direct-debits": {
      "get": {
        "tags": [
          "Banking",
          "Direct Debits"
        ],
        "summary": "Get Direct Debits For Account",
        "description": "Obtain direct debit authorisations for a specific account",
        "operationId": "listDirectDebits",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:regular_payments:read"
            ]
          },
          {
            "default": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/accounts/direct-debits": {
      "get": {
        "tags": [
          "Banking",
          "Direct Debits"
        ],
        "summary": "Get Bulk Direct Debits",
        "description": "Obtain direct debit authorisations for multiple, filtered accounts",
        "operationId": "listDirectDebitsBulk",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:regular_payments:read"
            ]
          },
          {
            "default": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      },
      "post": {
        "tags": [
          "Banking",
          "Direct Debits"
        ],
        "summary": "Get Direct Debits For Specific Accounts",
        "description": "Obtain direct debit authorisations for a specified list of accounts",
        "operationId": "listDirectDebitsSpecificAccounts",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:regular_payments:read"
            ]
          },
          {
            "default": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/accounts/{accountId}/payments/scheduled": {
      "get": {
        "tags": [
          "Banking",
          "Scheduled Payments"
        ],
        "summary": "Get Scheduled Payments for Account",
        "description": "Obtain scheduled, outgoing payments for a specific account",
        "operationId": "listScheduledPayments",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:regular_payments:read"
            ]
          },
          {
            "default": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/payments/scheduled": {
      "get": {
        "tags": [
          "Banking",
          "Scheduled Payments"
        ],
        "summary": "Get Scheduled Payments Bulk",
        "description": "Obtain scheduled payments for multiple, filtered accounts that are the source of funds for the payments",
        "operationId": "listScheduledPaymentsBulk",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:regular_payments:read"
            ]
          },
          {
            "default": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      },
      "post": {
        "tags": [
          "Banking",
          "Scheduled Payments"
        ],
        "summary": "Get Scheduled Payments For Specific Accounts",
        "description": "Obtain scheduled payments for a specified list of accounts",
        "operationId": "listScheduledPaymentsSpecificAccounts",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:regular_payments:read"
            ]
          },
          {
            "default": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/payees": {
      "get": {
        "tags": [
          "Banking",
          "Payees"
        ],
        "summary": "Get Payees",
        "description": "Obtain a list of pre-registered payees",
        "operationId": "listPayees",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:payees:read"
            ]
          },
          {
            "default": [
              "bank:payees:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/banking/payees/{payeeId}": {
      "get": {
        "tags": [
          "Banking",
          "Payees"
        ],
        "summary": "Get Payee Detail",
        "description": "Obtain detailed information on a single payee.\n\nNote that the payee sub-structure should be selected to represent the payment destination only rather than any known characteristics of the payment recipient",
        "operationId": "getPayeeDetail",
        "security": [
          {
            "PSUOAuth2Security": [
              "bank:payees:read"
            ]
          },
          {
            "default": [
              "bank:payees:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/common/customer": {
      "get": {
        "tags": [
          "Common",
          "Customer"
        ],
        "summary": "Get Customer",
        "description": "Obtain basic information on the customer that has authorised the current session",
        "operationId": "getCustomer",
        "security": [
          {
            "PSUOAuth2Security": [
              "common:customer.basic:read"
            ]
          },
          {
            "default": [
              "common:customer.basic:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    },
    "/common/customer/detail": {
      "get": {
        "tags": [
          "Common",
          "Customer"
        ],
        "summary": "Get Customer Detail",
        "description": "Obtain detailed information on the authorised customer within the current session.",
        "operationId": "getCustomerDetail",
        "security": [
          {
            "PSUOAuth2Security": [
              "common:customer.detail:read"
            ]
          },
          {
            "default": [
              "common:customer.detail:read"
            ]
          }
        ],
        "x-version": "1",
        "x-auth-type": "Application User",
        "x-throttling-tier": "Unlimited"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "PSUOAuth2Security": {
        "type": "oauth2",
        "description": "OAuth flow, it is required when the PSU needs to perform SCA with the ASPSP when a TPP wants to access an ASPSP resource owned by the PSU",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://openbank-secure.newcastlepermanent.com.au/authorize",
            "tokenUrl": "https://openbank-secure.newcastlepermanent.com.au/token",
            "scopes": {
              "bank:accounts.basic:read": "Basic Bank Account Data : This scope would allow for the third party to access basic information of the customer accounts. Includes simple account information including balance. Does not include account identifiers, product information or transaction data.",
              "bank:transactions:read": "Bank Transaction Data : This scope would allow the third party to access transaction data for accounts. This scope is effectively additional authorisation to the Basic Bank Account Data scope. Granting this authorisation only makes sense if the Basic Bank Account Data scope is also authorised.\nIncludes all account transaction data.",
              "bank:payees:read": "Bank Payee Data : This scope allows access to payee information stored by the customer .\nIncludes payee information such as billers, international beneficiaries and domestic payees.",
              "common:customer.basic:read": "Basic Customer Data : The scope would allow the third party to access personally identifiable information about the customer. For retail customers this would be information about the customer themselves. For business customers it would imply the name of specific user but also information about the business.\nIncludes name and occupation for individuals or name, business numbers and industry code for organisations",
              "bank:accounts.detail:read": "Detailed Bank Account Data : This scope would allow for the third party to access detailed information of the customer accounts. This scope is effectively additional authorisation to the Basic Bank Account Data scope. Granting this authorisation only makes sense if the Bank Account Data scope is also authorised.\nIncludes basic account information plus account identifiers and product information. Does not include transaction data.",
              "common:customer.detail:read": "Detailed Customer Data : The scope would allow the third party to access more detailed information about the customer. Includes the data available with the Basic Customer Data scope plus contact details.\nIncludes basic data plus phone, email and address information.",
              "bank:regular_payments:read": "Bank Regular Payments : The scope would allow the third party to access regular payments. Includes Direct Debits and Scheduled Payments.",
              "profile": "This scope value requests access to the End-User's default profile Claims, which are name, family_name, given_name, middle_name, nickname, preferred_username, profile, picture, website, gender, birthdate, zoneinfo, locale, and updated_at."
            }
          }
        },
        "x-scopes-bindings": {
          "bank:regular_payments:read": "Internal/subscriber",
          "bank:accounts.detail:read": "Internal/subscriber",
          "common:customer.detail:read": "Internal/subscriber",
          "bank:payees:read": "Internal/subscriber",
          "bank:transactions:read": "Internal/subscriber",
          "bank:accounts.basic:read": "Internal/subscriber",
          "common:customer.basic:read": "Internal/subscriber"
        }
      },
      "default": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://openbank-secure.newcastlepermanent.com.au/authorize",
            "tokenUrl": "https://openbank-secure.newcastlepermanent.com.au/token",
            "scopes": {
              "bank:accounts.basic:read": "Basic Bank Account Data : This scope would allow for the third party to access basic information of the customer accounts. Includes simple account information including balance. Does not include account identifiers, product information or transaction data.",
              "bank:transactions:read": "Bank Transaction Data : This scope would allow the third party to access transaction data for accounts. This scope is effectively additional authorisation to the Basic Bank Account Data scope. Granting this authorisation only makes sense if the Basic Bank Account Data scope is also authorised.\nIncludes all account transaction data.",
              "bank:payees:read": "Bank Payee Data : This scope allows access to payee information stored by the customer .\nIncludes payee information such as billers, international beneficiaries and domestic payees.",
              "common:customer.basic:read": "Basic Customer Data : The scope would allow the third party to access personally identifiable information about the customer. For retail customers this would be information about the customer themselves. For business customers it would imply the name of specific user but also information about the business.\nIncludes name and occupation for individuals or name, business numbers and industry code for organisations",
              "bank:accounts.detail:read": "Detailed Bank Account Data : This scope would allow for the third party to access detailed information of the customer accounts. This scope is effectively additional authorisation to the Basic Bank Account Data scope. Granting this authorisation only makes sense if the Bank Account Data scope is also authorised.Includes basic account information plus account identifiers and product information. Does not include transaction data.",
              "common:customer.detail:read": "Detailed Customer Data : The scope would allow the third party to access more detailed information about the customer. Includes the data available with the Basic Customer Data scope plus contact details.\nIncludes basic data plus phone, email and address information.",
              "bank:regular_payments:read": "Bank Regular Payments : The scope would allow the third party to access regular payments. Includes Direct Debits and Scheduled Payments.",
              "profile": "This scope value requests access to the End-User's default profile Claims, which are name, family_name, given_name, middle_name, nickname, preferred_username, profile, picture, website, gender, birthdate, zoneinfo, locale, and updated_at."
            }
          }
        },
        "x-scopes-bindings": {
          "bank:regular_payments:read": "Internal/subscriber",
          "bank:accounts.detail:read": "Internal/subscriber",
          "common:customer.detail:read": "Internal/subscriber",
          "bank:payees:read": "Internal/subscriber",
          "bank:transactions:read": "Internal/subscriber",
          "bank:accounts.basic:read": "Internal/subscriber",
          "common:customer.basic:read": "Internal/subscriber"
        }
      }
    }
  },
  "x-wso2-request-interceptor": "java:com.wso2.finance.open.banking.mg.interceptor.OpenBankingInterceptor",
  "x-wso2-response-interceptor": "java:com.wso2.finance.open.banking.mg.interceptor.OpenBankingInterceptor",
  "x-wso2-auth-header": "Authorization",
  "x-wso2-cors": {
    "corsConfigurationEnabled": false,
    "accessControlAllowOrigins": [
      "*"
    ],
    "accessControlAllowCredentials": false,
    "accessControlAllowHeaders": [
      "authorization",
      "Access-Control-Allow-Origin",
      "Content-Type",
      "SOAPAction",
      "apikey"
    ],
    "accessControlAllowMethods": [
      "GET",
      "PUT",
      "POST",
      "DELETE",
      "PATCH",
      "OPTIONS"
    ]
  },
  "x-wso2-production-endpoints": "#/x-wso2-endpoints/productionEndpoint",
  "x-wso2-sandbox-endpoints": "#/x-wso2-endpoints/sandboxEndpoint",
  "x-wso2-endpoints": [
    {
      "productionEndpoint": {
        "urls": [
          "https://localhost:9443/api/openbanking/backend-cds/services"
        ]
      }
    },
    {
      "sandboxEndpoint": {
        "urls": [
          "https://localhost:9443/api/openbanking/backend-cds/services"
        ]
      }
    }
  ],
  "x-wso2-basePath": "/cds-au/v1",
  "x-wso2-transports": [
    "http",
    "https"
  ],
  "x-wso2-response-cache": {
    "enabled": false,
    "cacheTimeoutInSeconds": 300
  },
  "x-original-swagger-version": "2.0"
}
